### PR TITLE
💄 Set fixed height of editor to keep toolbar visible

### LINKED ISSUE #26: Restrict Editor Size
Currently the menu scrolls out of view for long pages. It would make sense to restrict the editor window in size (we sure reuse the preference cookie for the size and also use the size control buttons)

### PR DESCRIPTION
**Pull request by micgro42**
This hides also the editor size controls, since they are not yet hooked up to the editor

Closes #26

### CODE REVIEW

File: script.js [hunk 1]
```diff
@@ -37,5 +37,6 @@ jQuery(() => {
     }
 
     jQuery('#wiki__text').hide();
+    jQuery('#size__ctl').hide();
```
Comment (splitbrain) [inline script.js]: we will want the size controls back later on. I'll merge this but we should keep the ticket open.
